openapi: 3.0.1
info:
  title: '@jupiterone/graph-panoptica'
  description: A JupiterOne Integration for ingesting data of the Panoptica
  x-cortex-git:
    github:
      repository: JupiterOne/graph-panoptica
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/graph-panoptica'
